### ISSUE TITLE
bug: popup colors

### ISSUE THREAD

**Issue by atomGit** [PerfectSlayer/scrollupfolder#75]
v `6.1.1resigned1`

the link font and link background colors in the popup are both black in my case

fix...

```css
@-moz-document url("moz-extension://[id]/popup/panel.html") {
    @layer {
        html, body {
            color: unset !important;
        }
    }
    div.panel div:hover {
        background-color: #444 !important;
    }
}
```
